<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create ' => 'Создать',
    'Dances' => 'Танцы',
    'Fresky' => 'Театр танца "Фрески"',
    'Gallery' => 'Галерея',
    'History' => 'История',
    'Login' => 'Логин',
    'Logout' => 'Выход',
    'News' => 'Новости',
    'Signup' => 'Вход',
    'Staff' => 'Танцоры',
    'Active' => 'Активный',
    'Album' => 'Альбом',
    'Albums' => 'Альбомы',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить запись?',
    'Body' => 'Тело',
    'Create' => 'Создать',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Email' => 'Почта',
    'Fullurl' => 'Полный url адрес',
    'Galleries' => 'Фотографии',
    'ID' => 'id',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Photo' => 'Фотография',
    'Photo list' => 'Список фотографий',
    'Start Date' => 'Дата создания',
    'Start Year' => 'Год создания',
    'Subject' => 'Тема',
    'Text' => 'Текст',
    'Title' => 'Заголовок',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => 'Редактировать {modelClass}: ',
    'Upload' => 'Загрузить',
    'Username' => 'Имя пользователя',
    'Verification Code' => 'Код подтверждения',
    'Year' => 'Год',
    '{modelname}' => 'Имя модели',
    'Image files' => 'Изображения'
];
